### PR TITLE
Add inline assets option

### PR DESCRIPTION
**Pull request by AMHOL**
Largely copied from https://github.com/simplecov-ruby/simplecov-html/pull/107

Uses a pretty hacky method to inline assets in the CSS, see https://github.com/simplecov-ruby/simplecov-html/pull/113/files#diff-ee98e028c59b193d58fde56ab4daf54d43c486ae674e63d50ddf300b07943e0fR38-R42

The following cucumber spec fails for me when running specs from simplecov with a local version of simplecov-html, from either this branch or master:

```
Expected `bundle exec rake minitest` to succeed but got non-zero exit status and the following output:

/home/andy/.rbenv/versions/2.7.0/bin/ruby -w -I"lib:minitest" /home/andy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/rake_test_loader.rb "minitest/other_test.rb" "minitest/some_test.rb" 
/home/andy/code/simplecov/lib/minitest/simplecov_plugin.rb:8:in `plugin_simplecov_init': undefined method `external_at_exit=' for SimpleCov:Module (NoMethodError)
	from /home/andy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/minitest-5.14.3/lib/minitest.rb:86:in `block in init_plugins'
	from /home/andy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/minitest-5.14.3/lib/minitest.rb:84:in `each'
	from /home/andy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/minitest-5.14.3/lib/minitest.rb:84:in `init_plugins'
	from /home/andy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/minitest-5.14.3/lib/minitest.rb:135:in `run'
	from /home/andy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/minitest-5.14.3/lib/minitest.rb:68:in `block in autorun'
rake aborted!
Command failed with status (1): [ruby -w -I"lib:minitest" /home/andy/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/rake_test_loader.rb "minitest/other_test.rb" "minitest/some_test.rb" ]
/home/andy/.rbenv/versions/2.7.0/bin/bundle:23:in `load'
/home/andy/.rbenv/versions/2.7.0/bin/bundle:23:in `<main>'
Tasks: TOP => minitest
(See full trace by running task with --trace)

 (RSpec::Expectations::ExpectationNotMetError)

Failing Scenarios:
cucumber features/minitest_basic.feature:44 # Scenario: Not having simplecov loaded/enabled it does not crash #877

89 scenarios (1 failed, 88 passed)
575 steps (1 failed, 1 skipped, 573 passed)
1m38.262s
```

I have loaded both the original and inline assets versions of the simplecov report in chrome and it all looks to be working to me.

### CODE REVIEW

**Comment by ohookins** [comment]
Any chance this could be merged? It would be super useful!

**Comment by AMHOL** [comment]
@ohookins @PragTob's profile currently says:

> hand/arm problems for 11 months+, getting better, slowly trying to get back

So I guess it may not be merged for a while, but you can pull it from my fork/branch:

```ruby
gem 'simplecov-html', git: 'git@github.com:AMHOL/simplecov-html.git', ref: '54a8c92b81bfc7b2ed051d9c4b9384d07d358ffc'
```

Or create your own fork from mine and pull from that.

**Comment by AMHOL** [comment]
I have rebased, fixed rubocop offenses and force-pushed.

**Comment by AMHOL** [comment]
@ohookins https://github.com/simplecov-ruby/simplecov-html/pull/107 has been merged :tada:

IIRC some images may be missing from that branch as it doesn't handle inlining of assets in CSS.

**Pull request closed without merging**
