### PR TITLE
Implement line number anchor

### LINKED ISSUE #49: Feature proposal: line number anchors
Using simplecov-html reports while doing active development is a bit painful right now:

1. I'm looking at the coverage report for a file, and find some missing lines. Let's say, hypothetically, they're lines 503-505.
2. Add tests that I think cover those lines and re-run my rspec rake task.
3. Refresh the coverage report in my browser and... I'm back at the top of the page and need to scroll to line 503 again.

My suggestion is to implement what some other HTML coverage generators do (i.e. Python's [coverage](https://coverage.readthedocs.io/en/coverage-4.2/index.html) package) - or, for that matter, GitHub when viewing source files or gists - and make each line number [a named anchor and link to that anchor](http://nedbatchelder.com/files/sample_coverage_html/cogapp_test_cogapp_py.html#n201) so that users can save their location in the file.

### PR DESCRIPTION
**Pull request by nishidayuya**
This pull-request includes following:

* Open `path_to_coverage/index.html#<file_id>-L<linenumber>` to display source code with scrolling to specified line number.
* Make source code line as hyperlink to `path_to_coverage/index.html#<file_id>-L<linenumber>`.

Closes #49

### CODE REVIEW

**Comment by nishidayuya** [comment]
Rebased from 7d1db362f612305979cf73947a6b823cbfada8f2 (old master branch) to 3a30b47964e74ac810edc02629d420fa1cb1bc12 (currently main branch)

This branch HEAD changed from 2d4a4aa79b6412986561ee62b6d50c00a0ab550a to 07fb07dd5fb9766076f5bf714fe4128fdfc9459e.

**Comment by nishidayuya** [comment]
Rebased from 3a30b47964e74ac810edc02629d420fa1cb1bc12 (old main branch) to 5bc5798aefed312abd189baed8a97bf1febfa8d7 (currently main branch)

This branch HEAD changed from 07fb07dd5fb9766076f5bf714fe4128fdfc9459e to eecec23a9b35cc97d182c650cbc365524dda8375.

**Comment by joshuapinter** [comment]
This would be **extremely** helpful! Can we please get this reviewed and merged in? 

The workflow of having to refresh the browser and scroll to the desired lines seems to be a common one.

Only thing that would make this better is the page auto refreshing when the coverage changes to reflect the coverage in real-time without any refreshes.

Thanks!

**Comment by joshuapinter** [comment]
@nishidayuya Mate, I just merged your branch into our fork and this is **so helpful**. Makes adding testes and refreshing the existing `index.html` browser tab so much faster. Thank you for doing this.

Anybody landing here looking for a solution, I suggest using @nishidayuya's fork until this gets merged into `main`, which doesn't look like it will happen anytime soon. I'm still waiting for a PR of my own to get merged in: #117.

**Comment by amatsuda** [comment]
This seems like a nice enhancement indeed. Thank you @jantman and @nishidayuya!

**Pull request merged**
