### PR TITLE
Print branch coverage with line coverage

### PR DESCRIPTION
**Pull request by jeremyevans**
Almost everyone using branch coverage is going to want to see the
branch coverage and the line coverage output.

### CODE REVIEW

**Comment by PragTob** [comment]
Hi @jeremyevans and thanks for your PR! Nice to see you around here :eyes: 

And yes it is, @tycooon was/is working on something for this but also including method coverage (which they're implementing). So I'd first wanna check with him before it gives him merge conflicts :D 

WhatsApp Image 2020-05-10 at 07 27 49

**Comment by gPrado** [comment]
Any news on this feature? It seems to be a very small PR, it must be simple to fix any eventual merge conflict.

**Review by Germanstreetstyle — APPROVED** [review]

**Comment by jeremyevans** [comment]
It's been over 2 years.  Can we please merge this or #117? As @gPrado mentioned, any merge conflict is likely to be small, so I'm not sure why that would block merging for two years.  @amatsuda is it possible you could review and merge this, since it looks like you merged the most recent commits?

**Review by winstonwolff — APPROVED** [review]
Looks great to me and I'd love to see it merged.

—Winston

**Comment by amatsuda** [comment]
Merging this one, finally. Sorry for leaving this simple patch open for 3 years.

I knew that this feature was missing, but I've been thinking that I'd better not do anything besides housekeeping because I'm not the original author nor the main maintainer of this repo.
Anyway, thank you @jeremyevans for the patch!

**Pull request merged**
